[workspace]
members = ["crates/prayertime-core", "crates/prayertime-cli", "crates/prayertime-wasm"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jiff = { version = "0.2", default-features = false, features = ["std"] }
jiff-tzdb = "0.1"
sha2 = "0.10"

[profile.release]
lto = true
opt-level = "s"
